default_platform(:ios)

platform :ios do

  before_all do
    UI.header "🚀 App Store Release"
    setup_circle_ci
  end

  lane :release do
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: "AuthKey_#{ENV["ASC_KEY_ID"]}.p8",
      in_house: false
    )

    match(
      type: "appstore",
      api_key: api_key,
      app_identifier: ENV["BUNDLE_ID"],
      readonly: false
    )

    gym(
      scheme: ENV["SCHEME"],
      export_method: "app-store",
      clean: true,
      xcargs: "-allowProvisioningUpdates"
    )

    deliver(
      api_key: api_key,
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: false
    )
  end

end